Rails.application.config.assets.precompile += %w( favicon.ico )
Rails.application.config.assets.precompile += %w( apple-touch-icon.png )
Rails.application.config.assets.precompile += %w( thecore.js )
Rails.application.config.assets.precompile += %w( thecore.css )
Rails.application.config.assets.precompile += %w( app_logo.png )
Rails.application.config.assets.precompile += %w( main_app_logo.png )
Rails.application.config.assets.precompile += %w( ie.js )
